export const registryImportCopy = {
  title: "Import Registry data",
  sourceEyebrow: "Registry source",
  reviewEyebrow: "Review parsed items",
  chooseFile: "Choose .reg file",
  chooseFileLabel: "Choose Registry file",
  pasteClipboard: "Paste from clipboard",
  cancel: "Cancel",
  replace: "Replace",
  addSource: "Add a Registry source",
  sourceHelp:
    "Choose a .reg file or paste copied Registry text. You can also drop a file on this panel.",
  pasteHintMac: "⌘V pastes while this dialog is open.",
  pasteHint: "Ctrl+V pastes while this dialog is open.",
  clipboardSource: "Clipboard",
  emptyClipboard: "Clipboard is empty.",
  emptyFile: "The selected file contains no Registry text.",
  partialHelp: "Skipped lines stay out of the import. Selected items can still be imported.",
  noParsedItems: "No Registry items could be parsed from this source.",
} as const;
