import type { AdministrativeTemplate } from "../../domain/admx";
import { templateNamespace } from "../../domain/admx";

export function administrativeTemplateImportInstructions(
  template: AdministrativeTemplate,
  admxFileName: string,
  admlFileName: string,
): string {
  const namespace = templateNamespace(template);
  return [
    "# Importing this administrative template",
    "",
    "This archive was generated by Endpoint Registry Studio. Custom ADMX import in Microsoft Intune is a public preview. Test the imported settings on a representative device before you assign the profile broadly.",
    "",
    "## Files",
    "",
    `- \`${admxFileName}\``,
    `- \`${admlFileName}\``,
    "",
    `Namespace: \`${namespace}\`. Template version: \`${template.version}\`.`,
    "",
    "## Import",
    "",
    "1. In Microsoft Intune, import the ADMX file and its en-US ADML file in the same step.",
    "2. Wait until the template status is available.",
    "3. Create a configuration profile that uses the imported template.",
    "4. Assign the profile only to test devices or test users.",
    "",
    "## Updating",
    "",
    "Uploading an ADMX file whose settings are already imported fails with a namespace error. Microsoft documents two options:",
    "",
    "1. Delete profiles that use the existing ADMX settings, delete the original imported ADMX file, then import the new ADMX and ADML files.",
    "2. Create a new ADMX file with a different namespace, preferably including a version number, then import that pair.",
    "",
    "## Limits",
    "",
    "- This template has no Windows.admx or Microsoft namespace dependency.",
    "- Only en-us language resources are included.",
    "- ExpandString Registry values are emitted as ADMX string values.",
    "- Intune Enabled, Disabled, and Not Configured states are not the same as Studio Detect or DryRun exact-state comparison.",
    "- LeaveExisting for Not Configured is rejected; ADMX cannot represent that behavior.",
    "- Review generated XML before import. Registry and Workspace content remains in the browser until you download this archive.",
    "",
  ].join("\n");
}
